kind: Service
apiVersion: v1
metadata:
  name: retf
spec:
  selector:
    app: retf
  ports:
    - name: metrics
      port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: retf
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: retf
  template:
    metadata:
      labels:
        app: retf
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: retf
          image: CONTAINER_IMAGE
          env:
            - name: PORT
              value: "80"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: retf-token
                  key: token
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: "1"
