version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - test
      # - push:
      #     requires:
      #       - test

jobs:
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker build -t app --target=test .
          docker run -it app
