version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
      - run: yarn compile
      - run: rm -rf dist
      - run: yarn test:ci
      - run: yarn lint:ci

  push_image:
    docker:
      - image: google/cloud-sdk:268.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          echo $GCP_TOKEN | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GCP_PROJECT}
          gcloud --quiet config set compute/zone ${GCP_ZONE}
      - run: |
          curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/v0.40.0/skaffold-linux-amd64;
          chmod +x /tmp/skaffold
      - run: /tmp/skaffold run

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push_image:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
