version: 2.1

orbs:
  docker: circleci/docker@1.5.0

workflows:
  version: 2
  build:
    jobs:
      - test
      - docker/publish:
          image: mplewis/discosay
          tag: latest,<< pipeline.git.tag >>
          update-description: true
          requires:
            - test
          filters:
            branches:
              only: master
            tags:
              only: /.*/

jobs:
  test:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: go test ./...
