version: 2
orbs:
  gcp-cli: circleci/gcp-cli@1.8.2

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
      - run: yarn compile
      - run: rm -rf dist
      - run: yarn test:ci
      - run: yarn lint:ci

  gcloud:
    docker:
      - image: ubuntu:bionic
    working_directory: ~/repo
    steps:
      - checkout
      - gcp-cli/install_and_initialize_cli:
          gcloud-service-key: GCP_TOKEN
          google-compute-zone: GCP_ZONE
          google-project-id: GCP_PROJECT

  # push_image:
  #   docker:
  #     - image: google/cloud-sdk:268.0.0
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run: scripts/build_and_push.sh
  #     - run: scripts/deploy.sh

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push_image:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
